### ISSUE TITLE
Feature request:  Front-end / Backend / Mixture toggle when running an automatic test.

### ISSUE THREAD

**Issue by atwellpub** [godaddy/wp-p3-profiler#4]
Hello Support, 

I've a plugin that is admittingly heavy on the wp-admin side, but light on the frontend side. Many times users who use P3 will contact me letting me know that the plugin costs too much in time-load resources and I notice that their test results come from the automatic testing feature of the P3 plugin profiler plugin. 

I'll let them know to perform a manual test and only access frontend files and their test results will improve. 

Could P3 possibly add the option to choose which side or sides the automatic test performs? I believe a pure frontend test should be the default. 

Cheers! 
-
Hudson Atwell

**Comment by frankiejarrett** [comment]
Hi @atwellpub, thanks for your question.

P3 is not currently in active feature development and has not received an update for a while now. After the release of PHP7 in Dec 2015, complications about P3's future surfaced (see #2) that have basically caused the project to pause until there is a clearer path for LTS.
